### PR TITLE
FX-508 Remove broken css link on careers page

### PR DESCRIPTION
**Pull request by brandonjmckay**

### CODE REVIEW

**Comment by joegaudet** [comment]
I'm not entirely sure what's going on here.

**Comment by brandonjmckay** [comment]
@joegaudet Pretty sure that IE is showing an alert box because it gets the same error that other browsers are getting, but reacts differently to it.

The error that all browsers were getting was that there is a style link to `/?ver=4.6` which gets sent as an `html` mime type instead of css. It also doesn't seem to resolve to any kind of actual css file so it is useless.

This removes the addition of that useless stylesheet, which I believe will fix the IE problem.

**Comment by romanchukenator** [comment]
Huh. I guess this is a 👍

**Comment by brandonjmckay** [comment]
I'll take it.

**Pull request merged**
